Server = 127.0.0.1
IP = 127.0.0.1
; server port number;
Port = 2812
DataPath = d:\develop\modelos\folha\
; path and name of a log file;
;LogPath = /tmp
; default RDD to open files on server ( CDX/NTX );
Default_Driver = CDX
;Lock_Scheme = 6
; memo type ( FPT/DBT ). Default: FPT for DBFCDX, DBT for DBFNTX;
;Memo_Type = FPT
; tables are opened in the same mode as client applications opens them, exclusive or shared
Share_Tables = 0
; When this mode is set, each dbUseArea() will cause a real file open operation and creating a new workarea on the server
No_Save_WA = 1
; if 1, convert all paths to lower case;
Lower_Path = 0
; if 1, using of file functions (leto_file(), leto_ferase(), leto_frename()) is enabled;
EnableFileFunc = 1
; if 1, creating of data tables and indexes with any extention, other than standard is enabled;
EnableAnyExt = 1
; if 1, using of udf functions is enabled;
Allow_UDF = 1
; if 1, user authentication is necessary to login to the server;
Pass_for_Login = 0
; if 1, user authentication is necessary to use management functions;
Pass_for_Manage = 0
; if 1, user authentication is necessary to have write access to the data;
Pass_for_Data = 0
; the path and name of users info file;
;Pass_File = leto_users
; The number of records to read into the cache
Cache_Records = 21
; Maximum number of shared variables
;Max_Vars_Number = 1000
; Maximim size of a text variable
;Max_Var_Size = 67108864
; Number of tables
;Tables_Max  = 999
; Number of users
;Users_Max = 99
; Debug level
Debug = 1
; if 1, SET HARDCOMMIT OFF
Optimize = 1
; SET AUTORDER setting
;AutOrder = 0
; _SET_FORCEOPT setting
;ForceOpt = 0
; connection timeout;
;TimeOut = 360
;Zombie_Check = 0
;Server_User = advantage
;Server_UID = 1000
;Server_GID = 4
;BC_Services = letodb;
;BC_Interface = eth2
;BC_Port = 2812
;SMB_SERVER = 1
; if 1, the data passes to the network encrypted;
Crypt_Traffic = 0
DataBase = /
Backup = /tmp/backup
Mask = *.dbf,*.dbt,*.ntx
Lock = 1
Seconds = 30
Wait = 1
ArcCmd = tar -cvzf /tmp/backup/leto.tar.gz /tmp/backup/*

; if 1, user authentication is necessary to be possible to use leto_RunAsync(), leto_RunSync() functions;
; Pass_for_Run = 1

; Global function letodb RDDI_TRIGGER
; Trigger = <cFuncName>

; Global function letodb RDDI_PENDINGTRIGGER
; PendingTrigger = <cFuncName>

; if 1, allows to change trigger settings, using dbInfo( DBI_TRIGGER, ... )
; EnableSetTrigger = 0

; It is possible to define [DATABASE] structure if you need to have a directory, where files are opened via other RDD:
;[DATABASE]
; Datapath =
; driver = cdx

;[PLAN_01]
; title=my first task
; Set days of a month when the task should start
; daysOfMonth=11, 16, 23, 26
; Or days of a week
; daysOfWeek=1, 3, 5
; Or set the number of days between task launches
; EveryNDay=2
; Set times of a day when the task should start
; TimeOfDay=11:10:00, 11:20:00, 14:29:00, 14:31:00
; Or set the number of seconds between task launches
; EveryNSec=2
; The full path to hrb or exe to launch
; Run=/mydir/tasks/1.hrb